version: '3.8' # версия формата файла Docker Compose

networks: #  объявление изолированных сетей для контейнеров
  monitoring: # создание сети с именем monitoring
    driver: bridge # тип сети «мост» для связи контейнеров на одном хосте

volumes: # объявление постоянных хранилищ (дисков)
  grafana-storage: # создание именованного диска для сохранения данных Grafana

services:
  redis:
    image: redis:7-alpine
    container_name: ai-agent-redis
    restart: unless-stopped # перезапускать контейнер всегда, кроме случая, когда он остановлен вручную.
    ports:
      - "6379:6379" # открыть порт 6379 (стандартный для Redis) наружу
    networks: # подключение к сетям
      - monitoring # добавить этот контейнер в созданную ранее сеть

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command: # переопределение стандартной команды запуска контейнера
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana
      # - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    environment: # переменные окружения
      - GF_SECURITY_ADMIN_PASSWORD=admin # установить стандартный пароль администратора (admin)
    depends_on:
      - prometheus # не запускать Grafana, пока не запустится сервис
    networks:
      - monitoring

  api:
    build:
      context: . # искать файлы для сборки в текущей папке.
      dockerfile: Dockerfile.api # использовать конкретный файл Dockerfile.api для сборки
    container_name: ai-agent-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./political_markers.yml:/app/political_markers.yml:ro # пробросить файл маркеров в режиме «только для чтения» (ro)
      - ./samples:/app/samples
    environment:
      YC_API_KEY: ${YC_API_KEY} # передать API-ключ Yandex Cloud из системы/файла .env.
      YC_FOLDER_ID: ${YC_FOLDER_ID}
    depends_on:
      - ai_classifier # запускать только после старта контейнера ai_classifier
    env_file:
      - .env # автоматически загрузить все скрытые переменные из локального файла .env
    networks:
      - monitoring

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: ai-agent-web
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - api #  запускать только после старта бэкенда (api)
    networks:
      - monitoring

  ai_classifier:
    build:
      context: .
      dockerfile: Dockerfile.ai_classifier
    container_name: ai_classifier
    restart: unless-stopped
    ports:
      - "8010:8001"
    volumes:
      - ./political_markers.yml:/app/political_markers.yml:ro
      - ./samples:/app/samples:ro
    environment:
      YC_API_KEY: ${YC_API_KEY}
      YC_FOLDER_ID: ${YC_FOLDER_ID}
      REDIS_URL: redis://redis:6379
    env_file:
      - .env
    networks:
      - monitoring

  browser:
    build:
      context: .
      dockerfile: Dockerfile.browser
    container_name: ai-agent-browser
    restart: unless-stopped
    ports:
      - "8011:8002"
    networks:
      - monitoring